[package]
name = "clickplanet-client"
version = "0.1.0"
edition = "2021"
description = "A Rust client for the ClickPlanet game"
license = "MIT"
repository = "https://github.com/valdo404/clickplanet-client"

[lib]
name = "clickplanet_client"
path = "src/lib.rs"

[[bin]]
name = "clickplanet-robot"
path = "src/main.rs"

[[bin]]
name = "clickplanet-tor"
path = "src/tor_test.rs"

[dependencies]
prost = "0.12"
tonic = "0.10"
tokio = { version = "1.0", features = ["full"] }
tokio-tungstenite = { version = "0.20", features = ["native-tls"] }
futures = "0.3"
url = "2.5"
native-tls = "0.2"
base64 = "0.21.7"
rand = "0.8.5"
reqwest = { version = "0.12.9", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.133"
arti-client = "0.25.0"
tor-rtcompat = "0.25.0"

[build-dependencies]
prost-build = "0.12"
