[application]

name = "clickplanet"

[web.app]

# HTML title tag content
title = "clickplanet"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
