[application]

name = "clickplanet"

[web.app]

# HTML title tag content
title = "clickplanet"

# include `assets` in web platform
script = []

[web.resource]
script = []
[[web.resource.copy-dir]]
src = "public/static"
dest = "static"
[[web.resource.copy-dir]]
src = "public/styles"
dest = "styles"

[web.resource.dev]
script = []

[[web.resource.dev.copy-dir]]
src = "public/static"
dest = "static"
[[web.resource.dev.copy-dir]]
src = "public/styles"
dest = "styles"
